name: shop_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^0.2.0
  flutter_svg: ^0.18.0 # help us to use SVG in our app
  provider: ^4.3.1 # for State management
  curved_navigation_bar: ^0.3.4
  cloud_firestore:
  firebase_auth:
  firebase_core:
  # flutter_launcher_icons: ^0.7.4
  flutter_spinkit: ^4.1.2+1
  flutter_rating_bar: ^3.2.0+1
  image_picker: ^0.6.6+5
  firebase_storage:
  connectivity:
  # data_connection_checker:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# flutter_icons:
#   image_path: 'assets/images/icon.jpg'
#   android: true
#   ios: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
  
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
